export const MAX_PARALLEL_TASKS = 8;
export const MAX_CONCURRENCY = 4;
export const COLLAPSED_ITEM_COUNT = 10;
export const PER_TASK_OUTPUT_CAP = 50 * 1024;
export const NESTED_SUBPROCESS_DETAIL_CAP = 20 * 1024;
export const MAX_NESTED_SUBPROCESSES_PER_RESULT = 16;
export const MAX_NESTED_RENDER_DEPTH = 3;
export const MAX_NESTED_RENDER_LINES = 80;
export const DEFAULT_COMMAND_TIMEOUT_MS = 10 * 60 * 1000;
export const MAX_SUBPROCESS_DEPTH = 5;
export const DEFAULT_CONTEXT_THRESHOLD = 0.6;
export const SUBPROCESS_STATE_ENTRY = "subprocess-state";
export const CURRENT_LOCATIONAL_ROOT_ENV = "PI_SUBPROCESS_LOCATIONAL_ROOT";
export const LOCATIONAL_ANCESTOR_STACK_ENV = "PI_SUBPROCESS_LOCATIONAL_STACK";
export const ADVERTISE_LOCATIONAL_AGENTS_ENV = "PI_SUBPROCESS_ADVERTISE_LOCATIONAL_AGENTS";
export const SUBPROCESS_CHILD_ENV = "PI_SUBPROCESS_CHILD";
export const ORCHESTRATED_CHILD_ENV = "PI_ORCHESTRATED_CHILD";
export const SUBPROCESS_DEPTH_ENV = "PI_SUBPROCESS_DEPTH";
export const DEFAULT_KNOWN_TOOLS = new Set([
	"bash",
	"read",
	"write",
	"edit",
	"ls",
	"find",
	"grep",
	"rg",
	"todo",
	"subprocess",
]);
