export const MAX_PARALLEL_TASKS = 8;
export const MAX_CONCURRENCY = 4;
export const COLLAPSED_ITEM_COUNT = 10;
export const PER_TASK_OUTPUT_CAP = 50 * 1024;
export const DEFAULT_COMMAND_TIMEOUT_MS = 10 * 60 * 1000;
export const MAX_SUBPROCESS_DEPTH = 5;
export const MAX_SUBAGENT_DEPTH = MAX_SUBPROCESS_DEPTH;
export const DEFAULT_CONTEXT_THRESHOLD = 0.6;
export const SUBPROCESS_STATE_ENTRY = "subprocess-state";
export const LEGACY_SUBAGENT_STATE_ENTRY = "subagent-state";
export const CURRENT_LOCATIONAL_ROOT_ENV = "PI_SUBPROCESS_LOCATIONAL_ROOT";
export const LEGACY_SUBAGENT_CURRENT_LOCATIONAL_ROOT_ENV = "PI_SUBAGENT_LOCATIONAL_ROOT";
export const LOCATIONAL_ANCESTOR_STACK_ENV = "PI_SUBPROCESS_LOCATIONAL_STACK";
export const LEGACY_SUBAGENT_LOCATIONAL_STACK_ENV = "PI_SUBAGENT_LOCATIONAL_STACK";
export const LEGACY_CURRENT_LOCATIONAL_ROOT_ENV = "PI_SUBAGENT_SKIP_LOCAL_SUBAGENTS";
export const ADVERTISE_LOCATIONAL_AGENTS_ENV = "PI_SUBPROCESS_ADVERTISE_LOCATIONAL_AGENTS";
export const LEGACY_ADVERTISE_LOCATIONAL_AGENTS_ENV = "PI_SUBAGENT_ADVERTISE_LOCATIONAL_AGENTS";
export const LEGACY_ADVERTISE_SOURCE_AGENTS_ENV = "PI_SUBAGENT_ADVERTISE_SOURCE_AGENTS";
export const SUBPROCESS_CHILD_ENV = "PI_SUBPROCESS_CHILD";
export const LEGACY_SUBAGENT_CHILD_ENV = "PI_SUBAGENT_CHILD";
export const ORCHESTRATED_CHILD_ENV = "PI_ORCHESTRATED_CHILD";
export const SUBPROCESS_DEPTH_ENV = "PI_SUBPROCESS_DEPTH";
export const LEGACY_SUBAGENT_DEPTH_ENV = "PI_SUBAGENT_DEPTH";
export const DEFAULT_KNOWN_TOOLS = new Set([
	"bash",
	"read",
	"write",
	"edit",
	"ls",
	"find",
	"grep",
	"rg",
	"todo",
	"subprocess",
	"subagent",
]);
